### ISSUE TITLE
Type / Build Error

### ISSUE THREAD

**Issue by Samayas1** [JDetmar/NLog.Extensions.AzureStorage#10]
In the file BlobStorageTarget.cs

On line 223 there is a typo in the conditional if

#if NESTANDARD 
            _appendBlob.AppendText(logMessage);
#else
            _appendBlob.AppendTextAsync(logMessage).GetAwaiter().GetResult();
#endif

Should be NETSTANDARD

However correcting it makes it a build error :

Error	CS1061	'CloudAppendBlob' does not contain a definition for 'AppendText' and no accessible extension method 'AppendText' accepting a first argument of type 'CloudAppendBlob' could be found (are you missing a using directive or an assembly reference?)	NLog.Extensions.AzureStorage(netstandard1.3), NLog.Extensions.AzureStorage(netstandard2.0)

**Comment by snakefoot** [comment]
Created #11 to resolve this
