### ISSUE TITLE
Don't write to AzureDataTables

### ISSUE THREAD

**Issue by m4ss1m0g** [JDetmar/NLog.Extensions.AzureStorage#110]
## Description

I have tried to write to AzureDataTables with a base example (see attached) without luck. 
I have tried several combinations, I have noticed that if the table does not exist it will create it and write once if I stop the program and re-run the message is not written.
If the table already exists it never writes to it.

I have attached a small console app following the Nlog official [.Net Core app](https://github.com/NLog/NLog/wiki/Getting-started-with-.NET-Core-2---Console-application)

## Environment
Windows 10 Pro
netcoreapp3.1

## Attachments
[TestAzure.zip](https://github.com/JDetmar/NLog.Extensions.AzureStorage/files/7261447/TestAzure.zip)

**Comment by snakefoot** [comment]
Can you include the output from the NLog InternalLogger: https://github.com/NLog/NLog/wiki/Internal-Logging

**Comment by m4ss1m0g** [comment]
Below are the files requested.

[internal-nlog.table.exists.txt](https://github.com/JDetmar/NLog.Extensions.AzureStorage/files/7261924/internal-nlog.table.exists.txt)
[internal-nlog.table.notexisits.txt](https://github.com/JDetmar/NLog.Extensions.AzureStorage/files/7261925/internal-nlog.table.notexisits.txt)

**Comment by snakefoot** [comment]
Very strange. There are no errors. 

**internal-nlog.table.notexisits.txt** says this:
2021-09-30 21:08:00.1656 Trace AzureTableStorageTarget(Name=azure): Requested Table Name: Foo
2021-09-30 21:08:00.5803 Debug AzureTableStorageTarget: Created table: Foo

**internal-nlog.table.exists.txt** says this:
2021-09-30 21:08:31.3233 Trace AzureTableStorageTarget(Name=azure): Requested Table Name: Foo

Curious if there is some flush/close-logic that needs to be improved. What happens if you run the application, and wait 30-60 secs before you **Press ANY key to exit**

**Comment by snakefoot** [comment]
You can also try to setup a `AzureEventSourceListener` that writes to console, and see if something is failing:

```c#
// Setup a listener to monitor logged events.
using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger();
```

See also: https://docs.microsoft.com/en-us/dotnet/api/overview/azure/data.tables-readme

**Comment by snakefoot** [comment]
Have also made a pull-request to improve the diagnostic logging in the AzureDataTables-NLog-target. See also: #111

You can download the [pre-release](https://ci.appveyor.com/project/JDetmar/nlog-extensions-azurestorage/builds/40977712/artifacts) nuget-package, and check if it gives some extra output:

https://ci.appveyor.com/api/buildjobs/yn8g4iq3rm8by8ln/artifacts/src%2FNLog.Extensions.AzureDataTables%2Fbin%2FRelease%2FNLog.Extensions.AzureDataTables.3.1.0.snupkg

**Comment by m4ss1m0g** [comment]
I've tried to:
1. Wait 60 seconds (no effect)
2. Added the `AzureEventSourceListener` it issue an error `409 Conflict`, below the entire log
```
2021-10-01 09:48:53.4700||DEBUG|TestAzure.Runner|Doing hard work! Action1|
Press ANY key to exit
[Informational] Azure-Core: Request [9b3b5712-88b8-45ab-80cf-eda8901ef7e5] POST https://xxxx.table.core.windows.net/Tables?$format=REDACTED
x-ms-version:REDACTED
DataServiceVersion:3.0
Accept:application/json; odata=minimalmetadata
x-ms-client-request-id:9b3b5712-88b8-45ab-80cf-eda8901ef7e5
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Data.Tables/12.1.0,(.NET Core 3.1.19; Microsoft Windows 10.0.19043)
x-ms-date:REDACTED
Authorization:REDACTED
Content-Type:application/json; odata=nometadata
client assembly: Azure.Data.Tables
[Warning] Azure-Core: Error response [9b3b5712-88b8-45ab-80cf-eda8901ef7e5] 409 Conflict (00.4s)
Cache-Control:no-cache
Transfer-Encoding:chunked
Server:Windows-Azure-Table/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id:e343fd6f-f002-0023-5e98-b6afa7000000
x-ms-client-request-id:9b3b5712-88b8-45ab-80cf-eda8901ef7e5
x-ms-version:REDACTED
X-Content-Type-Options:REDACTED
Date:Fri, 01 Oct 2021 07:48:55 GMT
Content-Type:application/json; odata=minimalmetadata; streaming=true; charset=utf-8
```
3. I can't install the 3.1.0 version because the nuget raise an error, I have tried also with net5.0
```
dotnet add package nlog.extensions.azuredatatables -v 3.1.0                                                                                                       
  Determining projects to restore...
  Writing C:\Users\massimo\AppData\Local\Temp\tmp6CC6.tmp
info : Adding PackageReference for package 'nlog.extensions.azuredatatables' into project 'D:\Temp\AzureDataTables\TestAzure\TestAzure.csproj'.
info : Restoring packages for D:\Temp\AzureDataTables\TestAzure\TestAzure.csproj...
error: NU1202: Package NLog.Extensions.AzureDataTables 3.1.0 is not compatible withnetcoreapp3.1 (.NETCoreApp,Version=v3.1). Package NLog.Extensions.AzureDataTables 3.1.0 does not support any target frameworks.
error: Package 'nlog.extensions.azuredatatables' is incompatible with 'all' frameworks in project 'D:\Temp\AzureDataTables\TestAzure\TestAzure.csproj'.
```
I have created a nuget.config pointing to local directory, and "pushed" your package.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        <add key="MyLocalSharedSource" value="d:\packages" />
    </packageSources>
</configuration>
```

Pushed with command
`nuget add D:\NLog.Extensions.AzureDataTables.3.1.0.snupkg -source d:\packages`

Do you have somewhere the updated source code (I can't find any branches on your git repo), I can try to add to my project and debug.

**Comment by snakefoot** [comment]
@m4ss1m0g Thank you for debugging this, and making a fix. Would be nice that it actually failed with an exception, instead of just silently doing nothing.

**Comment by snakefoot** [comment]
Created https://github.com/Azure/azure-sdk-for-net/issues/24378 for Microsoftt

**Comment by snakefoot** [comment]
@m4ss1m0g Guess the issue can be closed as resolved with https://www.nuget.org/packages/NLog.Extensions.AzureDataTables/3.1.0
