### ISSUE TITLE
Extracting values from Microsoft Azure Key Vault

### ISSUE THREAD

**Issue by snakefoot** [JDetmar/NLog.Extensions.AzureStorage#117]
@JDetmar Would it make sense to have NLog-package that can render values extracted from [Azure.Security.KeyVault.Secret](https://www.nuget.org/packages/Azure.Security.KeyVault.Secrets/) ? 

Could be like `${keyvaultsecret:item=mysecret}` (Similar to `${configsetting}` or `${appsetting}`)

**Comment by snakefoot** [comment]
Or would it just be overlapping with `${configsetting}`:

```c#
            if (context.HostingEnvironment.IsProduction())
            {
                var builtConfig = config.Build();
                var secretClient = new SecretClient(
                    new Uri($"https://{builtConfig["KeyVaultName"]}.vault.azure.net/"),
                    new DefaultAzureCredential());
                config.AddAzureKeyVault(secretClient, new KeyVaultSecretManager());
            }
```

See also: https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-6.0

**Comment by JDetmar** [comment]
That's interesting, I hadn't seen SecretClient
