### ISSUE TITLE
Container names cannot be nested

### ISSUE THREAD

**Issue by stuartdotnet** [JDetmar/NLog.Extensions.AzureStorage#128]
Because the safe naming code is stripping everything out, we're not able to add / to container names in the config in order to have them nested. Would be a nice addition if this was allowed

**Comment by snakefoot** [comment]
Pull-Requests are always wellcome.

**Comment by JDetmar** [comment]
Could you give an example of how you mean? I didn't believe container names allowed a '/' character.

**Comment by snakefoot** [comment]
I was guessing it was like this `/nested_subfolder/collection-name.log`

**Comment by stuartdotnet** [comment]
It looks like you're right that container names don't allow slashes, but, they do allow dashes, if that was something you feel is worth allowing. 
Here's the validation for container names: 
https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata

However Blob names are allowed slashes which is how you create virtual directories within a container. This was the functionality I was thinking of. https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata

This would be a little harder to implement in that it's not possible to add a nested container to the nlog config.

That being the case I'll close this for now.

**Comment by snakefoot** [comment]
Yes the nesting comes with the `BlobName` that has little validation.

The container-name is rather restrictive in that they allow (Only dashes and characters).
