### ISSUE TITLE
Azure EventHubs with Web Sockets possible?

### ISSUE THREAD

**Issue by hangy** [JDetmar/NLog.Extensions.AzureStorage#152]
Has anyone managed to use `NLog.Extensions.AzureEventHub` with AMQP over Web Sockets? [`Azure.Messaging.EventHubs`](https://github.com/Azure/azure-sdk-for-net/tree/487dc6d96269d22932a63a4d7608c0e5bdabb988/sdk/eventhub/Azure.Messaging.EventHubs) [can be configured to use web sockets](https://github.com/Azure/azure-sdk-for-net/blob/0fe487e2fb60cc142a49e7b74d59271b9eeb95ab/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample02_EventHubsClients.md#using-web-sockets) in code, but there doesn't seem to be an option to set the `AmqpWebSockets` transport in the for the  [EventHubTarget.EventHubService.Connect](https://github.com/JDetmar/NLog.Extensions.AzureStorage/blob/7a4424a4eb2c80868287ef038a48912cfe154b40/src/NLog.Extensions.AzureEventHub/EventHubTarget.cs#L473) method.

**Comment by snakefoot** [comment]
Created  #153 to add support for WebSockets. You can find custom nuget-package-artifacts here for testing:

https://ci.appveyor.com/project/JDetmar/nlog-extensions-azurestorage/builds/49044010/artifacts

**Comment by hangy** [comment]
Oh wow, I really didn't expect such a fast response, let alone a PR with a potential fix. Thank you! I'll gladly test the custom artifact.

**Comment by hangy** [comment]
Works quite well, as far as I can tell. I tested it with websockets, and a proxy. I didn't use a custom endpoint, because using the connection string just worked.

**Comment by JDetmar** [comment]
updated packages are now available on NuGet
https://www.nuget.org/packages/NLog.Extensions.AzureEventHub/4.4.0
https://www.nuget.org/packages/NLog.Extensions.AzureServiceBus/4.4.0

**Comment by hangy** [comment]
Thank you! 🙏
