### ISSUE TITLE
Not compatible with blob SAS tokens

### ISSUE THREAD

**Issue by edustaja** [JDetmar/NLog.Extensions.AzureStorage#28]
Blob storage allows to generate SAS tokens for **limited** permissions and time. 

Here is an example code to create SAS token for this library to use
 ```csharp
// Settings
var connectionString = "UseDevelopmentStorage=true";
var containerName = "nlog";
var expiryTime = DateTimeOffset.UtcNow.AddYears(5);

// Init storage account and create SAS token for container read
var storageAccount = CloudStorageAccount.Parse(connectionString);
var blobClient = storageAccount.CreateCloudBlobClient();
var container = blobClient.GetContainerReference(containerName);	
container.CreateIfNotExists();
var sasConstraints = new SharedAccessBlobPolicy();
sasConstraints.SharedAccessExpiryTime = expiryTime;
sasConstraints.Permissions = SharedAccessBlobPermissions.Write;
string sasToken = container.GetSharedAccessSignature(sasConstraints);

// The result connection string for nlog
var sasConnectionString =  $"BlobEndpoint={storageAccount.BlobEndpoint};SharedAccessSignature={sasToken}";
```

**Comment by jbennink** [comment]
This would be very nice. You could use a SAS uri that only allows writing to a specific container, but does not give full access like a connectionstring with AccountKey does.

**Comment by snakefoot** [comment]
PullRequests are always welcome. Then it will be tested code that is released.

**Comment by snakefoot** [comment]
Guess a special layout-renderer should be implemented to lookup (and refresh AccessToken). Then it can be integrated with TokenCredentials and StorageCredentials:

https://github.com/Azure/azure-storage-net/issues/895#issuecomment-520450269

Thus allowing assignment of `SharedAccessBlobPolicy`. The same AccessToken-LayutRenderer could also be used for other exciting stuff.

**Comment by haldarsumana** [comment]
How can I get a Sas url with read-only or write-only permission for a directory in Azure File Share to access all files and sub directory in that directory but it will not be accessible by other directory o files in Azure File Share by using Rest API?

**Comment by snakefoot** [comment]
When using `ServiceUri`-option for Blob-Target / Queue-Target, then it will use the "Azure AD credentials" of the application, to create a signed SAS (Aka. user delegation SAS). See also: https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-user-delegation-sas-create-dotnet
