### ISSUE TITLE
Support for sructured logging

### ISSUE THREAD

**Issue by anthony-sap** [JDetmar/NLog.Extensions.AzureStorage#32]
I am unable to get formatted or structured messages to appear in the TableStorage

target config
`<target name="AzureTableStorage" type="AzureTableStorage"
        tableName="auditLogs"        
      connectionStringKey="Nlog.Azure.BlobStorage.ConnectionString" >
        <layout type="JsonLayout" includeAllProperties="true">
          <attribute name="time" layout="${longdate}" />
          <attribute name="level" layout="${level:upperCase=true}"/>
          <attribute name="message" layout="${message}" />
        </layout>
      </target>`

I get this in the Azure table Storage

`{FullMessage: { "time": "2019-06-19 11:03:12.6477", "level": "DEBUG", "message": "{shopitem} added to basket by {user}" },
Message: {shopitem} added to basket by {user}
}`

It's called via the following 
`logger.Debug("{shopitem} added to basket by {user}", new { Id = 6, Name = "Jacket", Color = "Orange" }, "Kenny")`

**Comment by JDetmar** [comment]
@anthony-sap I was unable to reproduce the same log in Table Storage. I see the contents of FullMessage as:
```javascript
{
    "time": "2019-06-19 21:01:15.3335",
    "level": "DEBUG",
    "message": "{ Id = 6, Name = Jacket, Color = Orange } added to basket by \"Kenny\"",
    "shopitem": "{ Id = 6, Name = Jacket, Color = Orange }",
    "user": "Kenny"
}
```

This was just using the IntegrationTest project in the repo running .NET 4.5.2

What framework are you running?

**Comment by anthony-sap** [comment]
It's being used in a .NET 4.5 project, does it need to 4.5.2?
