### ISSUE TITLE
For local Blob Storage, it doesn't work

### ISSUE THREAD

**Issue by VikasJaiswal** [JDetmar/NLog.Extensions.AzureStorage#33]
I have used this extension of NLog and successfully uploaded the logs to Azure **Cloud** Blob Storage. But when I tried the same with a **local** blob storage, it silently fails. Below are the connection string formats for both:
**Azure Cloud Blob Storage Connection String**:- DefaultEndpointsProtocol=https;AccountName=**********;AccountKey=********;EndpointSuffix=core.windows.net

**Local Blob Storage Connection String**:- DefaultEndpointsProtocol=http;BlobEndpoint=http://{myhostname}:11002/localazureblob;AccountName=localazureblob;AccountKey=*******************************

It seems that it is not compatible with **Blob Endpoint** in the connection string.  The connection string is valid because I am able to upload some blob to this `localazureblob` account using other programs in the same environment.

**Comment by JDetmar** [comment]
@VikasJaiswal I believe you may be running into a limitation of the Storage Emulator. It does not support the Append Blob used by this library.

Please see this discussion on the Azure UserVoice
https://feedback.azure.com/forums/217298-storage/suggestions/10643412-provide-support-for-append-blobs-in-the-azure-stor

**Comment by VikasJaiswal** [comment]
Hi @JDetmar I am not using Append Blob feature. I am just trying to upload the logs to an azure blob container with the connection string in below format:
DefaultEndpointsProtocol=http;BlobEndpoint=http://{myhostname}:11002/localazureblob;AccountName=localazureblob;AccountKey=*******************************

However, I can successfully do the job when I use another connection string in below format:
DefaultEndpointsProtocol=https;AccountName=**********;AccountKey=********;EndpointSuffix=core.windows.net

But as I am using on premise azure blob, I have restriction to use first mentioned format. Please let me know if you need more details.

**Comment by JDetmar** [comment]
Sorry if I wasn't clear @VikasJaiswal . This extension is using a feature not supported in the emulator Append Blob seen here
https://github.com/JDetmar/NLog.Extensions.AzureStorage/blob/c0cd455e2e50a0e51d7d7f06fa831a4a2d6b4750/src/NLog.Extensions.AzureStorage/BlobStorageTarget.cs#L21

From the [Microsoft docs](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator#differences-between-the-storage-emulator-and-azure-storage) 

> Append Blob operations are not supported by the emulator. Attempting an operation on an append blob returns a FeatureNotSupportedByEmulator error (HTTP status code 400 - Bad Request).
