### ISSUE TITLE
connectionStringKey and appsettings.json

### ISSUE THREAD

**Issue by paulb2015** [JDetmar/NLog.Extensions.AzureStorage#36]
Is it possible to use connectionStringKey with a connection string from appsettings.json?

**Comment by frankely** [comment]
Are you getting any errors when you use that option?

**Comment by snakefoot** [comment]
@paulb2015 No you cannot use ConnectionStringKey to lookup appsettings.json values.

Instead you can use the ConnectionString-parameter to lookup ConnectionString in appsettings.json using `${configsetting}`.

Example:

```xml
<target type="AzureBlobStorage" connectionString="${configsetting=ConnectionStrings.MyConnectionString}">
</target>
```

With the following appsettings.json

```json
{
  "ConnectionStrings": {
    "MyConnectionString": "UseDevelopmentStorage=true;"
  },
}
```
See also https://github.com/NLog/NLog/wiki/ConfigSetting-Layout-Renderer

**Comment by paulb2015** [comment]
Thank you
