### ISSUE TITLE
Support for Azure EventHub ?

### ISSUE THREAD

**Issue by snakefoot** [JDetmar/NLog.Extensions.AzureStorage#37]
It could be nice to also have support for Azure Eventhub: 

https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-dotnet-standard-getstarted-send

But the dependencies for Azure EventHub are different, so it will have to be a new nuget-package. Ex. `NLog.Extensions.AzureEventHub` (With dependency on [Microsoft.Azure.EventHubs](https://www.nuget.org/packages/Microsoft.Azure.EventHubs/))

@JDetmar If I created a PR that introduces a new NLog.Extensions.AzureEventHub.csproj file that generates a new nuget-package. Would you be willing to take it in and publish on nuget.org?

**Comment by JDetmar** [comment]
@snakefoot absolutely!
You are right event hub is certainly a desirable target. That would be a very nice addition. I could make use of it myself.

**Comment by snakefoot** [comment]
> What are your thoughts?

Will try and make the EventHubTarget, and see how the logic flows compared to the existing.

But looking at the API then it is very similar to the others with partitioning LogEvents on PartitionKey and sending in batches.

**Comment by snakefoot** [comment]
Resolved with #39
