### ISSUE TITLE
Connection String Key is assumed to come from AppSettings

### ISSUE THREAD

**Issue by grahambunce** [JDetmar/NLog.Extensions.AzureStorage#4]
If you set a connection string in the ConnectionString section of the app.config it is not found. This is only found when you add it to the AppSettings section.

When running in Azure App Services the recommended practice is to store connection strings in the Connection Strings section so that they can be encrypted / hidden by Azure. It's also more logical to the unwary that a connection string key would be found in the connection string section.

The logic should check one or the other first and then fallback to check the alternative location.

**Comment by JDetmar** [comment]
thanks for that

**Comment by grahambunce** [comment]
@JDetmar no worries. Can you push a new NuGet package please so I can pick up the change?
