### ISSUE TITLE
WindowsAzure.Storage split in multiple packages

### ISSUE THREAD

**Issue by snakefoot** [JDetmar/NLog.Extensions.AzureStorage#42]
Maybe also split this package into multiple sub-packages with their own direct dependency:

https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob/
https://www.nuget.org/packages/Microsoft.Azure.Storage.File/
https://www.nuget.org/packages/Microsoft.Azure.Storage.Queue/
https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table/

> Note: As of 10.0.0, the namespace has changed to Microsoft.Azure.Storage.Common, .Blob, .File, and .Queue. This is required for some SxS scenarios.

> Note: As of 9.4.0, the Table service is not supported by this library. Table support is being provided by CosmosDB.

See also: https://www.nuget.org/packages/WindowsAzure.Storage/ (Stops being updated)

https://github.com/Azure/azure-storage-net/blob/master/README.md

**Comment by JDetmar** [comment]
It's a good point. It would fall in line with the direction Microsoft took the libraries.

**Comment by JDetmar** [comment]
I have begun to take a shot at breaking it out
https://github.com/JDetmar/NLog.Extensions.AzureStorage/tree/v2

**Comment by snakefoot** [comment]
I have started on the same task but including rewrite to use AsyncTaskTarget.


Was thinking to change the original nuget package to be a meta-package that references the new nuget-packaged


Sent from my Sony Xperia


---- Justin Detmar wrote ----


I have begun to take a shot at breaking it out
https://github.com/JDetmar/NLog.Extensions.AzureStorage/tree/v2

**Comment by JDetmar** [comment]
Excellent idea. I'd love to see what you have come up with. I was also hoping to update to the AsyncTaskTarget.

I noticed the namespace used for the event Hub target. Is that a better standard for writing targets?

**Comment by snakefoot** [comment]
Have implemented blob and table storage. Missing the queue. But would also like some simple unit tests, and not just the integration test


Sent from my Sony Xperia


---- Justin Detmar wrote ----


Excellent idea. I'd love to see what you have come up with. I was also hoping to update to the AsyncTaskTarget.

I noticed the namespace used for the event Hub target. Is that a better standard for writing targets?

**Comment by snakefoot** [comment]
@JDetmar Create initial attempt for splitting into packages. Not very skilled with naming and structure. Any suggestions that makes it easier for you are certainly welcome.

**Comment by StefH** [comment]
@snakefoot what are the issues with keeping the meta package ?

**Comment by snakefoot** [comment]
@StefH Because you still need to update your NLog.config to include the individual packages. Ex:

```xml
<nlog>
<extensions>
  <add assembly="NLog.Extensions.AzureEventHub" /> 
  <add assembly="NLog.Extensions.AzureStorageBlob" /> 
  <add assembly="NLog.Extensions.AzureStorageTable" /> 
  <add assembly="NLog.Extensions.AzureStorageQueue" /> 
</extensions>
</nlog>
```

Else the logic will not work in NetCore with package-references, where the dlls cannot be discovered automatically by the NLog-engine.

Instead of having too ways of using the packages, then I prefer just one and with less confusion. If you know how to make meta-package works automatically on NetCore, then please tell.

**Comment by StefH** [comment]
Can't you just soft-link all the source files from the 3 projects? In that you can can have 1 NuGet which contains all code.

For an example see
- https://github.com/scottksmith95/LINQKit/blob/master/src/LinqKit/LinqKit.csproj#L33
- https://github.com/StefH/QboxNext/blob/master/src/QboxNext/QboxNext.csproj#L42

**Comment by snakefoot** [comment]
> Can't you just soft-link all the source files from the 3 projects?

Then you will have 1 package that contains the same classes as the 3 other projects. That will give more confusion that it actually helps. The different nuget-packages will then have a hard time living together in the same project (example want a newer version of one of the packages).
