### ISSUE TITLE
Unable to write to blob storage

### ISSUE THREAD

**Issue by abirstolov** [JDetmar/NLog.Extensions.AzureStorage#49]
I'm unable to write to azure blob storage:
Settings (partial for brevity):
```
 <extensions>
    <add assembly="NLog.Web.AspNetCore"/>
    <add assembly="NLog.Extensions.AzureBlobStorage" />
  </extensions>

 <target xsi:type="AzureBlobStorage" name="azure" 
      container="logs" 
      connectionString="**REMOVED**" 
      blobName="test.log" 
      layout="${longdate}|${event-properties:item=EventId_Id}|${pad:padding=-5:inner=${uppercase:${level}}}|${logger:shortName=true}|${message} ${exception:format=tostring}|url: ${aspnet-request-url}|action: ${aspnet-mvc-action}" />
  
```
Internal log:
> Error AzureBlobStorageTarget: Failed to initialize blob=test.log in container=logs Exception: System.NullReferenceException: Object reference not set to an instance of an object.
>    at NLog.Targets.BlobStorageTarget.CloudBlobService.InitializeContainer(String containerName, CancellationToken cancellationToken)
>    at NLog.Targets.BlobStorageTarget.CloudBlobService.InitializeAndCacheBlobAsync(String containerName, String blobName, String contentType, CancellationToken cancellationToken)

I have a _logs_ container in the said storage  
any idea?

**Comment by snakefoot** [comment]
Thank you for reporting this. Was a little too quick when I did the refactoring to create unit-test-mocks.

Created #50 to resolve the bug.

**Comment by snakefoot** [comment]
[NLog.Extensions.AzureBlobStorage](https://www.nuget.org/packages/NLog.Extensions.AzureBlobStorage/) ver. 2.0.1 has been released. Thank you @JDetmar
