### ISSUE TITLE
ContentType for blobs is always set to application/octet-stream

### ISSUE THREAD

**Issue by jlpstolwijk** [JDetmar/NLog.Extensions.AzureStorage#52]
It seems that contentType property for AzureBlob target is not working correctly. My log files always get the "application/octet-stream" type, even if I set contentType explicitly to "text/plain".

I have the following settings in Nlog.config:
```
<target xsi:type="AzureBlobStorage"
  name="azureBlobLogs"
  layout="${longdate} | ${uppercase:${level}} | Origin: ${aspnet-request-referrer} | RequestUrl: ${aspnet-request-url} | UserId: ${aspnet-user-identity} | ${logger} ${newline}${message} ${newline}${onexception:${exception:format=tostring}${newline}}"
  connectionString="(myconnectionstring)"
  container="${date:universalTime=true:format=yyyy}"
  blobName="${date:universalTime=true:format=yyyyMMdd}.log"
  contentType="text/plain" />
```
And it results in the following log files in Azure Storage:

![image](https://user-images.githubusercontent.com/47030980/66823798-3f95a900-ef47-11e9-89e7-b06b8f28f966.png)

(Running .NetCore 2.2, NLog.Extensions.AzureStorage 1.1.4)

**Comment by snakefoot** [comment]
Could you try with this new and updated target: https://www.nuget.org/packages/NLog.Extensions.AzureBlobStorage/ ?

**Comment by snakefoot** [comment]
Never mind. Created PR #55 to resolve this.

**Comment by snakefoot** [comment]
Could you try with this new and updated target: https://www.nuget.org/packages/NLog.Extensions.AzureBlobStorage/ ?

It assigns the ContentType Property before creating the blob, so it should work correctly.

**Comment by jlpstolwijk** [comment]
Thanks a lot, it works correctly with the new package!
