### ISSUE TITLE
New API - Azure.Storage.Blobs + Azure.Storage.Queues

### ISSUE THREAD

**Issue by snakefoot** [JDetmar/NLog.Extensions.AzureStorage#58]
Yet again a new [Azure.Storage.Blobs](https://www.nuget.org/packages/Azure.Storage.Blobs/) API has been introduced:

https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-customer-provided-key

Same for [Azure.Storage.Queues](https://www.nuget.org/packages/Azure.Storage.Queues/).

There is also a new [Azure.Messaging.EventHubs](https://www.nuget.org/packages/Azure.Messaging.EventHubs/) but still in beta.

Curious if new libraries will arrive for Microsoft.Azure.Cosmos.Table. Right now it seems `Microsoft.Azure.Cosmos` will not be changed.

**Comment by JDetmar** [comment]
They only kept on Microsoft.Azure for a year. That was short.

Looks like this is the readme to watch
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/README.md

**Comment by snakefoot** [comment]
A possible up-to-date list of Azure SDK packages:

https://azure.github.io/azure-sdk/releases/latest/index.html

**Comment by snakefoot** [comment]
While implementing #62 then I thought I would move to the "new packages" for authentications and lookup of AccessToken.

But found several Github-issues about missing features, and it was still work inprogress, and they should become stable over the summer. Not sure if that "deadline" is stable, when everyone is doing the Corona dance.

**Comment by snakefoot** [comment]
Looks like these are now complete:
- Event Hubs
- Storage - Blobs
- Storage - Queues

These are still in BETA:
- Azure Cosmos Database
- Azure Identity for AccessToken (Ver. 1.2 was released, but 1.3-preview is the version you want)

These are new:
- Storage - Files Shares
