### ISSUE TITLE
Support native .net standard packages

### ISSUE THREAD

**Issue by grahambunce** [JDetmar/NLog.Extensions.AzureStorage#6]
Provide .net standard packages. I guess this also means a change to supported azure dependencies too?

NB: if I was to provide a pull request for this, would your build infrastructure support making the packages?

**Comment by snakefoot** [comment]
Created PR #7

**Comment by snakefoot** [comment]
@JDetmar Created PR #7

**Comment by snakefoot** [comment]
@grahambunce You can find a pre-release nuget-package here:

https://ci.appveyor.com/project/JDetmar/nlog-extensions-azurestorage/build/1.0.12/artifacts
