### ISSUE TITLE
Can't get Azure Table Storage to work

### ISSUE THREAD

**Issue by jamesyolk** [JDetmar/NLog.Extensions.AzureStorage#70]
I'm using .net core 3.1 and latest NLog.Extensions.AzureCosmosTable v2.5.0. But I can't seem to get Azure Table Storage to work. I was able to use the Blob nuget to work but no luck with this. My `nlog.config` is something like this:
```
<?xml version="1.0" encoding="utf-8" ?>
<nlog
        xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <extensions>
        <add assembly="NLog.Extensions.AzureCosmosTable" />
    </extensions>
        
    <targets>
      <target xsi:type="AzureTableStorage"
              name="azure"
              PartitionKey="${date}"
              RowKey="${ticks}"
              connectionString=""
              tableName="TestLogsDev">
      </target>
    </targets>
    
    <rules>
        <logger name="*" minlevel="Debug" writeTo="azure"/>
    </rules>
</nlog>
```
Anyone know what's wrong with my config?

**Comment by JDetmar** [comment]
Hi @jamesyolk ,
A few items I see here.
First is the partition key. Using the date layout will result in disallowed characters 
https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-the-table-service-data-model#characters-disallowed-in-key-fields

Second is the target type `<target xsi:type="AzureTableStorage">` this should actually be `<target xsi:type="AzureCosmosTable">`

I hope that helps

**Comment by jamesyolk** [comment]
@JDetmar, thank you for the solution, it worked wonderfully! 
Sorry I forgot to respond and close the issue earlier.
