### ISSUE TITLE
MessageSizeExceededException

### ISSUE THREAD

**Issue by adrianignat13** [JDetmar/NLog.Extensions.AzureStorage#71]
Hi,

Using NLog.Extensions.AzureEventHub, Version=2.4.0.0, we get MessageSizeExceededException once in a while when it's trying to write to EventHub. We have a filter in place to drop messages greater than 51200 characters. 

Here is how the config looks like:
```
<target xsi:type="AzureEventHub" name="EventHub" connectionString="$(EVENT-HUB-CONNECTION-STRING)" partitionKey="some-partition-key">
        <layout type="JsonLayout" includeAllProperties="true" suppressSpaces="true" MaxRecursionLimit="3">
          <attribute name="level" layout="${level}" />
          <attribute name="logger" layout="${logger}" />
          <attribute name="user" layout="${mdlc:item=User}" />
        </layout>
</target>
```

```
<logger ruleName="ruleName" name="name" writeTo="EventHub" final="true">
        <filters defaultAction='Log'>
          <when condition="length('${message}') &gt; 51200" action="IgnoreFinal" />
          <when DistantTime hoursInTheFuture="24" hoursInThePast="744" action="IgnoreFinal"/>
        </filters>
</logger>
```

My assumptions are as follows:
1. If there is one large message, than the filter is not applied. Is this related to the library or NLog itself?
2. If there is a batch of messages, shouldn't the library make sure that it will never create a batch that will be rejected by EventHub?

**Comment by snakefoot** [comment]
Created #72 to make the dynamic batchsize calculation more conservative.

**Comment by snakefoot** [comment]
@adrianignat13 Please try if this [pre-release ](https://ci.appveyor.com/project/JDetmar/nlog-extensions-azurestorage/builds/34626889/artifacts)nuget-package resolves your problem:

https://ci.appveyor.com/api/buildjobs/lcardlc8cevmdnms/artifacts/src%2FNLog.Extensions.AzureEventHub%2Fbin%2FRelease%2FNLog.Extensions.AzureEventHub.2.5.0.nupkg

Just download to a local nuget-repository and try it out.

**Comment by snakefoot** [comment]
@adrianignat13 NLog.Extensions.AzureEventHub ver. 2.5.0 has been released:

https://www.nuget.org/packages/NLog.Extensions.AzureEventHub/

**Comment by snakefoot** [comment]
NLog.Extensions.AzureEventHub ver. 2.6.0 has been released, and has new option `MaxBatchSizeBytes` with default value 1 MByte (Basic Tier = 256 KByte, Standard Tier = 1 MByte)

https://www.nuget.org/packages/NLog.Extensions.AzureEventHub/
