### ISSUE TITLE
why does Blob tags are only supported on General Purpose v2 storage accounts? how do i fix it?

### ISSUE THREAD

**Issue by weiyilai** [JDetmar/NLog.Extensions.AzureStorage#87]
2021-01-14 10:53:07.3039 Error AzureBlobStorageTarget: Failed to initialize blob=stevenlai.log in container=fastip-t Exception: Azure.RequestFailedException: Blob tags are only supported on General Purpose v2 storage accounts.
RequestId:e1502eae-b01e-0089-4620-ea6fe4000000
Time:2021-01-14T02:53:07.2459717Z
Status: 400 (Blob tags are only supported on General Purpose v2 storage accounts.)
ErrorCode: BlobTagsNotSupportedForAccountType

Headers:
x-ms-request-id: e1502eae-b01e-0089-4620-ea6fe4000000
x-ms-client-request-id: 6c950fc3-e073-4f2d-ae2c-034bdeae79a9
x-ms-version: 2019-12-12
x-ms-error-code: BlobTagsNotSupportedForAccountType
Date: Thu, 14 Jan 2021 02:53:06 GMT
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
Content-Length: 271
Content-Type: application/xml

   於 Azure.Storage.Blobs.BlobRestClient.AppendBlob.CreateAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
   於 Azure.Storage.Blobs.BlobRestClient.AppendBlob.<CreateAsync>d__0.MoveNext()
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 System.Threading.Tasks.ValueTask`1.get_Result()
   於 System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   於 Azure.Storage.Blobs.Specialized.AppendBlobClient.<CreateInternal>d__23.MoveNext()
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 Azure.Storage.Blobs.Specialized.AppendBlobClient.<CreateIfNotExistsInternal>d__22.MoveNext()
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 Azure.Storage.Blobs.Specialized.AppendBlobClient.<CreateIfNotExistsAsync>d__19.MoveNext()
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 NLog.Targets.BlobStorageTarget.CloudBlobService.<InitializeBlob>d__9.MoveNext()
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   於 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   於 NLog.Targets.BlobStorageTarget.CloudBlobService.<InitializeAndCacheBlobAsync>d__8.MoveNext()

**Comment by snakefoot** [comment]
Sounds like a question for Microsoft or StackOverflow:

- https://docs.microsoft.com/en-us/azure/storage/common/storage-account-upgrade
- https://docs.microsoft.com/en-us/azure/storage/common/storage-account-overview

**Comment by weiyilai** [comment]
thanks a lot, we upgrade v2 account, it's solve.

**Comment by snakefoot** [comment]
@weiyilai Happy to hear. Please close the issue, if you feel it has been resolved.
