### ISSUE TITLE
Initialization Error in _container

### ISSUE THREAD

**Issue by Samayas1** [JDetmar/NLog.Extensions.AzureStorage#9]
In the file BlobStorageTarget.cs

When logging in async mode 2 consecutive logs 

Ex:
               logger.Info("Info");
               logger.Warn("Warning");

NLog calls override method Write(IList<AsyncLogEventInfo> logEvents)
Since there are more than 1 logEvents the base.Write Doesn't get called and InitializeContainer(containerName) doesn't initiate the _container.

This causes a System.NullReferenceException exception on line 163  _appendBlob = _container.GetAppendBlobReference(blobName);

A possible fix would be to add InitializeContainer(containerName) on line 127.

This was working in version 1.0.6

**Comment by snakefoot** [comment]
Created #11 to resolve this
