### ISSUE TITLE
AzureBlobStorage no longer support ConnectionStringKey

### ISSUE THREAD

**Issue by bart-rosseel** [JDetmar/NLog.Extensions.AzureStorage#92]
We have been using the NLog.Extensions.AzureStorage package in its latest version for a while. On the AzureBlobStorage target type this supported the "ConnectionStringKey" property , which allows to define ConnectionString in appsettings or connectionstrings section of the config. This was very helpful in keeping the connectionstring secret confidential and out of source control.
Moving to the newer NLog.Extensions.AzureBlobStorage package reveals that this property is no longer supported. 
I am wondering if this is by design and if there are plans of adding back this property ?

**Comment by snakefoot** [comment]
NLog Layout-logic allows you to load the ConnectionString-value from anywhere you like.

**NetCore example of how to access the appsettings.json**

> `${configsetting:item=ConnectionStrings.AzureBlob}`

Example appsettings.json:

```json
{
  "ConnectionStrings": {
    "AzureBlob": "UseDevelopmentStorage=true;"
  }
}
```

**.NetFramework example of how to access the app.config**

> `${appsetting:item=ConnectionStrings.AzureBlob}`

Example app.config:

```xml
<configuration>
  <connectionStrings>
    <add name="ElasticUrl" connectionString="http://localhost:9200"/>
  </connectionStrings>
</configuration>
```

You can also use the [NLog GDC](https://github.com/NLog/NLog/wiki/Gdc-layout-renderer).

**Comment by snakefoot** [comment]
@bart-rosseel Have your question been answered, so you can close the issue?

**Comment by bart-rosseel** [comment]
@snakefoot Yes, thank you. Issue closed.

**Comment by snakefoot** [comment]
Now also updated the docs: https://github.com/JDetmar/NLog.Extensions.AzureStorage/blob/master/src/NLog.Extensions.AzureBlobStorage/README.md#azure-connectionstring
