### ISSUE TITLE
Not able to set logTimeStampFormat while configuraing target as AzureCosmosTable

### ISSUE THREAD

**Issue by myschandru** [JDetmar/NLog.Extensions.AzureStorage#97]
I am trying to insert all logs into AzureCosmosTable and logs are getting inserted successfully however not able to change the format of logTimeStampFormat. DateTime is getting inserted in epoc format and not able to configure to the DateTime in ISO format.

**Comment by myschandru** [comment]
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Trace"
      internalLogFile="Logs/internallog.txt">

	<extensions>
		<add assembly="NLog.Extensions.AzureTable" />
		<add assembly="NLog.Extensions.AzureCosmosTable" />
	</extensions>

	<time type="AccurateUTC" />
  <targets async="true">
	  <target xsi:type="AzureCosmosTable"
		name="cosmostable"
		connectionString="xxxxxxxx"
		tableName="xxxxxxxx"
		layout="JSON"	
		partitionKey ="${date:format=yyyy-MM-dd}"
		logTimeStampFormat ="O">
		<attribute name="logTimeStamp" 
           layout="${date:format=O}" />
		<contextproperty name="Level" layout="${level:upperCase=true}" />
		<contextproperty name="logger" layout="${logger}" />
		<contextproperty name="threadId" layout="${threadid}" />
		<contextproperty name="machinename" layout="${machinename}" />
		<contextproperty name="username" layout="${mdlc:item=UserName}" />
		<contextproperty name="message" layout="${message}" />
	</target>
  </targets>

  <rules>
	<logger name="*" minlevel="Debug" writeTo="cosmostable" />
  </rules>
</nlog>

**Comment by snakefoot** [comment]
Cannot see any attempt to set LogTimeStampFormat. Please try again.


Sent from my Sony Xperia


---- myschandru wrote ----


<extensions>
        <add assembly="NLog.Extensions.AzureTable" />
        <add assembly="NLog.Extensions.AzureCosmosTable" />
</extensions>

<time type="AccurateUTC" />

**Comment by myschandru** [comment]
yes, with after trying several times still getting logTimeStamp in EPOC time only.

**Comment by snakefoot** [comment]
Your task is to show the content of your NLog. config so one can see how you attempt to set LogTimeStampFormat


Sent from my Sony Xperia


---- myschandru wrote ----


yes, after trying several times still getting logTimeStamp in EPOC time only.

**Comment by snakefoot** [comment]
If you are not using Nlog.config, and if you are creating the table-target programmatically then you need to present the code. Remember we are not sitting next to you in your basement


Sent from my Sony Xperia


---- myschandru wrote ----


yes, after trying several times still getting logTimeStamp in EPOC time only.

**Comment by myschandru** [comment]
Request you to have some patience, I had already pasted my nlog.con. I am pasting it again below.

<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Trace"
      internalLogFile="Logs/internallog.txt">

	<extensions>
		<add assembly="NLog.Extensions.AzureTable" />
		<add assembly="NLog.Extensions.AzureCosmosTable" />
	</extensions>

	<targets>
		<target xsi:type="AzureCosmosTable"
			name="cosmostable"
			connectionString="xxxxxxxx"
			tableName="xxxx"
			layout="JSON"
			partitionKey ="${date:format=yyyy-MM-dd}"
			logTimeStampFormat ="O">
			<attribute name="logTimeStamp"
			   layout="${date:format=O}" />
			<contextproperty name="Level" layout="${level:upperCase=true}" />
			<contextproperty name="logger" layout="${logger}" />
			<contextproperty name="threadId" layout="${threadid}" />
			<contextproperty name="machinename" layout="${machinename}" />
			<contextproperty name="username" layout="${mdlc:item=UserName}" />
			<contextproperty name="message" layout="${message}" />
		</target>

		<target name="logfile" xsi:type="File"
				fileName="Logs/${shortdate}_logfile.txt" archiveAboveSize="5000000"
				layout="${longdate} ${level:uppercase=true} ${message}"/>
	</targets>

	<rules>
		<logger name="*" minlevel="Debug" writeTo="cosmostable" />
	</rules>
</nlog>

I am not creating the Cosmos table manually, NLog is creating the table and below is how it is writing logs into Cosmos table. No custom code has been written apart from above Nlog config

{
    "id": "2517846886334317786__18eac9f7-a5cc-4740-9c9e-4bb730bf8b4d",
    "LogTimeStamp": {
        "$t": 9,
        "$v": "00637532089665682213"
    },
    "Level": {
        "$t": 2,
        "$v": "INFO"
    },
    "logger": {
        "$t": 2,
        "$v": "Host.Triggers.Warmup"
    },
    "threadId": {
        "$t": 2,
        "$v": "5"
    },
    "machinename": {
        "$t": 2,
        "$v": "ELL0014"
    },
    "username": {
        "$t": 2,
        "$v": ""
    },
    "message": {
        "$t": 2,
        "$v": "Initializing Warmup Extension."
    },
    "$pk": "2021-04-05",
    "$id": "2517846886334317786__18eac9f7-a5cc-4740-9c9e-4bb730bf8b4d",
    "_rid": "U9Z-AO36G4gBAAAAAAAAAA==",
    "_self": "dbs/U9Z-AA==/colls/U9Z-AO36G4g=/docs/U9Z-AO36G4gBAAAAAAAAAA==/",
    "_etag": "\"53009ba1-0000-0200-0000-606acd8f0000\"",
    "_attachments": "attachments/",
    "_ts": 1617612175
}

**Comment by snakefoot** [comment]
Thank you for  showing the content of your NLog.config-file. The reason for saving `logTimeStamp` as DateTime is to save space.

But I guess I can make an exception, so if the first `<contextproperty>` has `name="logTimeStamp"`, then it can be used to override the column with whatever random string-value:

```xml
	<target xsi:type="AzureCosmosTable"
		name="cosmostable"
		connectionString="xxxxxxxx"
		tableName="xxxx"
		layout="JSON"
		partitionKey ="${date:format=yyyy-MM-dd}">
	   <contextproperty name="LogTimeStamp" layout="${date:format=O}" />
	   <contextproperty name="message" layout="${message}" />
	</target>
```

**Comment by snakefoot** [comment]
Created #98 to resolve this issue.

**Comment by myschandru** [comment]
Thank you for your response, however the above mentioned solution doesn't work. It results in the following error which is logged in the NLog interlog

AzureTableStorageTarget(Name=cosmostable): Failed to write table=rbacLogs Exception: System.ArgumentException: An item with the same key has already been added. Key: LogTimeStamp
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at NLog.Targets.TableStorageTarget.CreateTableEntity(LogEventInfo logEvent, String partitionKey)
   at NLog.Targets.TableStorageTarget.GenerateBatch(IEnumerable`1 logEvents, String partitionId)
   at NLog.Targets.TableStorageTarget.WriteAsyncTask(IList`1 logEvents, CancellationToken cancellationToken)

**Comment by snakefoot** [comment]
Happy you are eager to test the solution. But you need to wait for the mentioned pull-request to be merged and update to latest nuget package


Sent from my Sony Xperia


---- myschandru wrote ----


Thank you for your response, however the above mentioned solution doesn't work. It results in the following error which is logged in the NLog interlog

AzureTableStorageTarget(Name=cosmostable): Failed to write table=rbacLogs Exception: System.ArgumentException: An item with the same key has already been added. Key: LogTimeStamp
at System.Collections.Generic.Dictionary2.TryInsert(TKey key, TValue value, InsertionBehavior behavior) at System.Collections.Generic.Dictionary2.Add(TKey key, TValue value)
at NLog.Targets.TableStorageTarget.CreateTableEntity(LogEventInfo logEvent, String partitionKey)
at NLog.Targets.TableStorageTarget.GenerateBatch(IEnumerable1 logEvents, String partitionId) at NLog.Targets.TableStorageTarget.WriteAsyncTask(IList1 logEvents, CancellationToken cancellationToken)

**Comment by snakefoot** [comment]
@myschandru  Please try and update to latest version: https://www.nuget.org/packages/NLog.Extensions.AzureCosmosTable/2.8.0
